[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sanjustin"
authors = [{name = "Justin Skycak"}, {name = "Sanjana Kulkarni"}]
dynamic = ["version", "description"]
